version: '2'
services:
  web:
    container_name: web
    build: ./build/web
    command: gunicorn ecommerce.wsgi:application -b 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - '.:/code'
      - 'django_admin:/usr/local/lib/python3.9/site-packages/django/contrib/admin/static'
    networks:
      - net
    depends_on:
      - db

  db:
    image: postgres
    container_name: db_web
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - './data:/var/lib/postgresql/data:rw'
    networks:
      - net

  proxy:
    container_name: web-proxy
    build: ./build/proxy
    restart: always
    ports:
      - '80:80'
    command: nginx -g 'daemon off;'
    volumes:
      - './build/proxy/nginx.conf:/etc/nginx/nginx.conf'
      - './static:/var/www/static'
      - './media:/var/www/media'
      - django_admin:/var/www/django_admin/static
    depends_on:
      - web
    networks:
      - net

networks:
  net:
    external: true

volumes:
  django_admin:

