version: '2'
services:
  web:
    container_name: '${SERVICE_NAME}'
    build: ./build/web
    command: '${CMD_PROD}'
    ports:
      - '8000:8000'
    volumes:
      - '.:/code'
      - 'django_admin:/usr/local/lib/python3.9/site-packages/django/contrib/admin/static'
    networks:
      - net
    depends_on:
      - db

  db:
    image: 'postgres:${POSTGRES_VERSION}'
    container_name: '${SERVICE_NAME}-db'
    environment:
      - POSTGRES_DB='${SERVICE_NAME}_db'
      - POSTGRES_USER='${POSTGRES_USER}'
      - POSTGRES_PASSWORD='${POSTGRES_PASSWORD}'
    volumes:
      - './data:/var/lib/postgresql/data:rw'
    networks:
      - net

  proxy:
    container_name: '${SERVICE_NAME}-PROXY'
    build: ./build/proxy
    restart: always
    ports:
      - '80:80'
    command: nginx -g 'daemon off;'
    volumes:
      - './build/proxy/nginx.conf:/etc/nginx/nginx.conf'
      - './static:/var/www/static'
      - './media:/var/www/media'
      - django_admin:/var/www/django_admin/static
    depends_on:
      - web
    networks:
      - net

networks:
  net:
    external: true

volumes:
  django_admin:

