# Generated by Django 3.2.8 on 2021-10-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211023_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 's'), ('m', 'M'), ('l', 'L')], max_length=100, null=True),
        ),
    ]
